image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

  CI_DOCKER_COMPOSE_SERVICE_MASTER_NAME: sca-pipeline-api-master
  CI_DOCKER_COMPOSE_SERVICE_SLAVE_NAME: sca-pipeline-api-slave
  CI_REGISTRY_IMAGE_MASTER: project/vosint/$CI_DOCKER_COMPOSE_SERVICE_MASTER_NAME
  CI_REGISTRY_IMAGE_SLAVE: project/vosint/$CI_DOCKER_COMPOSE_SERVICE_SLAVE_NAME
  GIT_DEPTH: "3"

stages:
  - deploy-pro

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

deploy-pro:
  stage: deploy-pro
  image: alpine:latest
  timeout: 5 hours 30 minutes
  
  tags:
    - production
  only:
    - production
  before_script:
    - apk --no-cache add ca-certificates
    - apk add --no-cache rsync
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo -e "$DS0_RSA_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
  script:
    - ssh -p $PRO_SERVER_SSH_PORT ds1@$PRO_SERVER_HOST "cd $PRO_SOURCE_PATH; git pull; git checkout production; git pull; sed -i 's/consumer.py/main.py/g' Dockerfile;  docker build --pull -t "$CI_REGISTRY/$CI_REGISTRY_IMAGE_MASTER:sca" -f Dockerfile .; docker service update --image $CI_REGISTRY/$CI_REGISTRY_IMAGE_MASTER:sca --with-registry-auth --force '${PRO_DOCKER_STACK_NAME}_${CI_DOCKER_COMPOSE_SERVICE_MASTER_NAME}'; sed -i 's/main.py/consumer.py/g' Dockerfile;  docker build --pull -t "$CI_REGISTRY/$CI_REGISTRY_IMAGE_SLAVE:sca" -f Dockerfile .; docker service update --image $CI_REGISTRY/$CI_REGISTRY_IMAGE_SLAVE:sca --with-registry-auth --force '${PRO_DOCKER_STACK_NAME}_${CI_DOCKER_COMPOSE_SERVICE_SLAVE_NAME}-1'; docker service update --image $CI_REGISTRY/$CI_REGISTRY_IMAGE_SLAVE:sca --with-registry-auth --force '${PRO_DOCKER_STACK_NAME}_${CI_DOCKER_COMPOSE_SERVICE_SLAVE_NAME}-2'; docker service update --image $CI_REGISTRY/$CI_REGISTRY_IMAGE_SLAVE:sca --with-registry-auth --force '${PRO_DOCKER_STACK_NAME}_${CI_DOCKER_COMPOSE_SERVICE_SLAVE_NAME}-3'; docker service update --image $CI_REGISTRY/$CI_REGISTRY_IMAGE_SLAVE:sca --with-registry-auth --force '${PRO_DOCKER_STACK_NAME}_${CI_DOCKER_COMPOSE_SERVICE_SLAVE_NAME}-4'; docker service update --image $CI_REGISTRY/$CI_REGISTRY_IMAGE_SLAVE:sca --with-registry-auth --force '${PRO_DOCKER_STACK_NAME}_${CI_DOCKER_COMPOSE_SERVICE_SLAVE_NAME}-5'"
