version: '3.6'
services:
    vosint-pipeline-salve08-1:
        image: vienai/vosint-pipeline-slave:1.0.2
        ports: 
            - 8111:6101        
        environment:           
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong5.vosint.edu.vn:60005,mong6.vosint.edu.vn:60006/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_KEYWORD_API=http://vosint-extraction-hpc08:1510/api/extraction
            - DOCUMENT_CLUSTERING_API=http://vosint-templateclassify-hpc08:1510/document_clustering
            - SENTIMENT_API=http://vosint-sentiment-hpc08:1510/topic
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
            - KEYWORD_CLUSTERING_API=http://vosint-keywordclassify-hpc08:1510/document_keyword
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
            placement:
                constraints:
                  - node.hostname==hpc08         
        networks:
            - vosint3_system_network
    
    vosint-pipeline-salve08-2:
        image: vienai/vosint-pipeline-slave:1.0.2
        ports: 
            - 8121:6101        
        environment:           
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong5.vosint.edu.vn:60005,mong6.vosint.edu.vn:60006/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_KEYWORD_API=http://vosint-extraction-hpc08:1510/api/extraction
            - DOCUMENT_CLUSTERING_API=http://vosint-templateclassify-hpc08:1510/document_clustering
            - SENTIMENT_API=http://vosint-sentiment-hpc08:1510/topic
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
            - KEYWORD_CLUSTERING_API=http://vosint-keywordclassify-hpc08:1510/document_keyword
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
            placement:
                constraints:
                  - node.hostname==hpc08            
        networks:
            - vosint3_system_network
            
    vosint-pipeline-salve08-3:
        image: vienai/vosint-pipeline-slave:1.0.2
        ports: 
            - 8131:6101        
        environment:           
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong5.vosint.edu.vn:60005,mong6.vosint.edu.vn:60006/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_KEYWORD_API=http://vosint-extraction-hpc08:1510/api/extraction
            - DOCUMENT_CLUSTERING_API=http://vosint-templateclassify-hpc08:1510/document_clustering
            - SENTIMENT_API=http://vosint-sentiment-hpc08:1510/topic
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
            - KEYWORD_CLUSTERING_API=http://vosint-keywordclassify-hpc08:1510/document_keyword
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
            placement:
                constraints:
                  - node.hostname==hpc08            
        networks:
            - vosint3_system_network
            
    vosint-pipeline-salve08-4:
        image: vienai/vosint-pipeline-slave:1.0.2
        ports: 
            - 8141:6101        
        environment:           
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong5.vosint.edu.vn:60005,mong6.vosint.edu.vn:60006/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_KEYWORD_API=http://vosint-extraction-hpc08:1510/api/extraction
            - DOCUMENT_CLUSTERING_API=http://vosint-templateclassify-hpc08:1510/document_clustering
            - SENTIMENT_API=http://vosint-sentiment-hpc08:1510/topic
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
            - KEYWORD_CLUSTERING_API=http://vosint-keywordclassify-hpc08:1510/document_keyword
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
            placement:
                constraints:
                  - node.hostname==hpc08           
        networks:
            - vosint3_system_network
            
    vosint-pipeline-salve08-5:
        image: vienai/vosint-pipeline-slave:1.0.2
        ports: 
            - 8151:6101        
        environment:           
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong5.vosint.edu.vn:60005,mong6.vosint.edu.vn:60006/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_KEYWORD_API=http://vosint-extraction-hpc08:1510/api/extraction
            - DOCUMENT_CLUSTERING_API=http://vosint-templateclassify-hpc08:1510/document_clustering
            - SENTIMENT_API=http://vosint-sentiment-hpc08:1510/topic
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
            - KEYWORD_CLUSTERING_API=http://vosint-keywordclassify-hpc08:1510/document_keyword
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
            placement:
                constraints:
                  - node.hostname==hpc08            
        networks:
            - vosint3_system_network
    
    vosint-pipeline-salve08-6:
        image: vienai/vosint-pipeline-slave:1.0.2
        ports: 
            - 8161:6101        
        environment:           
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong5.vosint.edu.vn:60005,mong6.vosint.edu.vn:60006/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_KEYWORD_API=http://vosint-extraction-hpc08:1510/api/extraction
            - DOCUMENT_CLUSTERING_API=http://vosint-templateclassify-hpc08:1510/document_clustering
            - SENTIMENT_API=http://vosint-sentiment-hpc08:1510/topic
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
            - KEYWORD_CLUSTERING_API=http://vosint-keywordclassify-hpc08:1510/document_keyword
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
            placement:
                constraints:
                  - node.hostname==hpc08           
        networks:
            - vosint3_system_network

    vosint-pipeline-salve08-7:
        image: vienai/vosint-pipeline-slave:1.0.2
        ports: 
            - 8171:6101        
        environment:           
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong5.vosint.edu.vn:60005,mong6.vosint.edu.vn:60006/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_KEYWORD_API=http://vosint-extraction-hpc08:1510/api/extraction
            - DOCUMENT_CLUSTERING_API=http://vosint-templateclassify-hpc08:1510/document_clustering
            - SENTIMENT_API=http://vosint-sentiment-hpc08:1510/topic
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
            - KEYWORD_CLUSTERING_API=http://vosint-keywordclassify-hpc08:1510/document_keyword
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
            placement:
                constraints:
                  - node.hostname==hpc08            
        networks:
            - vosint3_system_network

    vosint-pipeline-salve08-8:
        image: vienai/vosint-pipeline-slave:1.0.2
        ports: 
            - 8181:6101        
        environment:           
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong5.vosint.edu.vn:60005,mong6.vosint.edu.vn:60006/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_KEYWORD_API=http://vosint-extraction-hpc08:1510/api/extraction
            - DOCUMENT_CLUSTERING_API=http://vosint-templateclassify-hpc08:1510/document_clustering
            - SENTIMENT_API=http://vosint-sentiment-hpc08:1510/topic
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
            - KEYWORD_CLUSTERING_API=http://vosint-keywordclassify-hpc08:1510/document_keyword
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
            placement:
                constraints:
                  - node.hostname==hpc08            
        networks:
            - vosint3_system_network

    vosint-pipeline-salve08-9:
        image: vienai/vosint-pipeline-slave:1.0.2
        ports: 
            - 8191:6101        
        environment:           
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong5.vosint.edu.vn:60005,mong6.vosint.edu.vn:60006/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_KEYWORD_API=http://vosint-extraction-hpc08:1510/api/extraction
            - DOCUMENT_CLUSTERING_API=http://vosint-templateclassify-hpc08:1510/document_clustering
            - SENTIMENT_API=http://vosint-sentiment-hpc08:1510/topic
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
            - KEYWORD_CLUSTERING_API=http://vosint-keywordclassify-hpc08:1510/document_keyword
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
            placement:
                constraints:
                  - node.hostname==hpc08           
        networks:
            - vosint3_system_network

    vosint-pipeline-salve08-10:
        image: vienai/vosint-pipeline-slave:1.0.2
        ports: 
            - 8201:6101        
        environment:           
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong5.vosint.edu.vn:60005,mong6.vosint.edu.vn:60006/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_KEYWORD_API=http://vosint-extraction-hpc08:1510/api/extraction
            - DOCUMENT_CLUSTERING_API=http://vosint-templateclassify-hpc08:1510/document_clustering
            - SENTIMENT_API=http://vosint-sentiment-hpc08:1510/topic
            - TRANSLATE_API=http://vosint-translate-hpc08:1510/api/translate
            - KEYWORD_CLUSTERING_API=http://vosint-keywordclassify-hpc08:1510/document_keyword
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
            placement:
                constraints:
                  - node.hostname==hpc08           
        networks:
            - vosint3_system_network

networks: 
  vosint3_system_network:
    external: true

