version: '3.6'
services:
    vosint-pipeline-master:
        image: vienai/vosint-pipeline-master:1.0.0
        ports: 
            - 6101:6101        
        environment:
            MONGO_CONNECTION: mongodb://admin:kttv%400258@192.168.1.71:14680/admin?authSource=admin&authMechanism=SCRAM-SHA-256
            ENVIRONMENT: PRODUCTION
            MONGO_DETAILS: mongodb://admin:aivosint%400258@mong2.vosint.edu.vn:60002,mong3.vosint.edu.vn:60003/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            DATABASE_NAME: vosint_db
            KAFKA_CONNECT: kafka-1:9092,kafka-2:9092,kafka-3:9092
            ELASTIC_CONNECT: http://master1:9200,http://master2:9200,http://master3:9200
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1        
        networks:
            - vosint3_system_network

networks: 
  vosint3_system_network:
    external: true

