version: "3"

services:
  vosint_mongo:
    image: mongo
    container_name: vosint_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: vosint_db
      MONGO_INITDB_ROOT_USERNAME: vosint
      MONGO_INITDB_ROOT_PASSWORD: vosint_2022
    expose:
      - 27017
    ports:
      - 27017:27017
    command: mongod --bind_ip_all
    networks:
      - vosint_net

  vosint_swagger_ui:
    image: swaggerapi/swagger-ui
    container_name: vosint_swagger_ui
    restart: always
    environment:
      SWAGGER_JSON: /openapi.json
    volumes:
      - ./swagger/openapi.json:/openapi.json
    expose:
      - 8080
    ports:
      - 3200:8080
    networks:
      - vosint_net

networks:
  vosint_net:
    driver: bridge
